version: '3.8'
services:
  backend:
    build:
      context: ../
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ../
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "8501:8501"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge